/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaAdministracion;

import Negocio.Opciones;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author frenk
 */
public class JFAsiento_SalaUnido extends javax.swing.JFrame {

    DefaultTableModel modeloSala,modeloAsiento,modeloAsiento_Sala;
    Opciones op;
    String formato;
    int idSala; //llavePrimariaSala
    int idAsiento;//llavePrimariaAsiento
    int auxDisponibilidad,pktablaAsiento,pktablaSala,pktablaAsientoSala;
    //tabla sala
    int idTablaSala=2;
       String[] TitulosSala={"IdSala","Tipo"};
       String nombreTablaSala = "SELECT * FROM sala";
       
    //tabla asiento
    int idTablaAsiento=3;
     String[] TitulosAsiento={"IdAsiento","Fila","Columna"};
     String nombreTablaAsiento = "SELECT * FROM asiento";
     
    //tabla asientosala
     int idTablaAS=4;
       String[] TitulosAS={"IdAsiento_Sala","IdSalaA","IdAsientoS","Disponibilidad"};
       String nombreTablaAS = "SELECT * FROM asiento_sala";
    public JFAsiento_SalaUnido() {
        initComponents();
        setLocationRelativeTo(null);
        //tabla sala 
         modeloSala = new DefaultTableModel();
        modeloSala.addColumn("# de Sala");
        modeloSala.addColumn("Tipo");
        TablaSala.setModel(modeloSala);
        //tabla asiento
        modeloAsiento = new DefaultTableModel();
        modeloAsiento.addColumn("# Asiento");
        modeloAsiento.addColumn("Fila");
        modeloAsiento.addColumn("Columna");
        TablaAsiento.setModel(modeloAsiento);
        //tabla asiento sala
        modeloAsiento_Sala = new DefaultTableModel();
        modeloAsiento_Sala.addColumn("# Asiento-Sala");
        modeloAsiento_Sala.addColumn("# de Sala");
        modeloAsiento_Sala.addColumn("# de Asiento");
        modeloAsiento_Sala.addColumn("Disponibilidad");
        TablaAsiento_Sala.setModel(modeloAsiento_Sala);
        //
        op = new Opciones();
        op.cargarTabla(modeloSala, TablaSala, nombreTablaSala, TitulosSala, idTablaSala);
        op.cargarTabla(modeloAsiento, TablaAsiento, nombreTablaAsiento, TitulosAsiento, idTablaAsiento);
        op.cargarTabla(modeloAsiento_Sala, TablaAsiento_Sala, nombreTablaAS, TitulosAS, idTablaAS);
        ImageIcon limpiar= new ImageIcon(getClass().getResource("/Imagenes/borrar.png"));
        ImageIcon icono = new ImageIcon (limpiar.getImage(
        ).getScaledInstance(btnLimpiar.getWidth(),btnLimpiar.getHeight(),Image.SCALE_DEFAULT));
        btnLimpiar.setIcon(icono);
        btnLimpiar.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaAsiento = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        JBAgregarAsiento = new javax.swing.JButton();
        JBEliminarAsiento = new javax.swing.JButton();
        btnActualizarAsiento = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTFIdAsiento1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFColumna = new javax.swing.JTextField();
        btnLimpiar2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTFFila = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaSala = new javax.swing.JTable();
        btnLimpiar1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnAgregrarSala = new javax.swing.JButton();
        btnEliminarSala = new javax.swing.JButton();
        btnActualizarSala = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFSala = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbmFormato = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JBAgregarAS = new javax.swing.JButton();
        JBEliminarAS = new javax.swing.JButton();
        btnActualizarAS = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAsiento_Sala = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdAsientoSala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jTFIdAsiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFIdSala = new javax.swing.JTextField();
        cbmDisponibilidad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Pelicula = new javax.swing.JMenuItem();
        Sala = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asiento");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Asiento:"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("(Seleccione la asiento deseada)");

        TablaAsiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdAsiento", "Fila", "Columna"
            }
        ));
        TablaAsiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAsientoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaAsiento);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        JBAgregarAsiento.setText("Agregar");
        JBAgregarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarAsientoActionPerformed(evt);
            }
        });

        JBEliminarAsiento.setText("Eliminar");
        JBEliminarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarAsientoActionPerformed(evt);
            }
        });

        btnActualizarAsiento.setText("Actualizar");
        btnActualizarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAsientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBAgregarAsiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(JBEliminarAsiento)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarAsiento)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(JBAgregarAsiento)
                .addComponent(JBEliminarAsiento)
                .addComponent(btnActualizarAsiento))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del asiento"));

        jLabel11.setText("IdAsiento");

        jTFIdAsiento1.setEditable(false);
        jTFIdAsiento1.setEnabled(false);

        jLabel12.setText("Columna");

        jTFColumna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFColumnaKeyTyped(evt);
            }
        });

        btnLimpiar2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnLimpiar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Fila");

        jTFFila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFFilaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFIdAsiento1)
                    .addComponent(jTFColumna)
                    .addComponent(jTFFila, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTFIdAsiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTFFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sala:"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("(Seleccione la sala deseada)");

        TablaSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdSala", "Formato"
            }
        ));
        TablaSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSalaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaSala);

        btnLimpiar1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnLimpiar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnAgregrarSala.setText("Agregar");
        btnAgregrarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregrarSalaActionPerformed(evt);
            }
        });

        btnEliminarSala.setText("Eliminar");
        btnEliminarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSalaActionPerformed(evt);
            }
        });

        btnActualizarSala.setText("Actualizar");
        btnActualizarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregrarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAgregrarSala)
                .addComponent(btnEliminarSala)
                .addComponent(btnActualizarSala))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la sala"));

        jLabel7.setText("Id de la Sala");

        jTFSala.setEditable(false);
        jTFSala.setEnabled(false);

        jLabel10.setText("Formato");

        cbmFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 2D", "Sala 4D", "Sala VIP" }));
        cbmFormato.setSelectedIndex(-1);
        cbmFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmFormatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFSala)
                    .addComponent(cbmFormato, 0, 125, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbmFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        JBAgregarAS.setText("Agregar");
        JBAgregarAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarASActionPerformed(evt);
            }
        });

        JBEliminarAS.setText("Eliminar");
        JBEliminarAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarASActionPerformed(evt);
            }
        });

        btnActualizarAS.setText("Actualizar");
        btnActualizarAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JBAgregarAS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarAS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBEliminarAS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBEliminarAS)
                    .addComponent(JBAgregarAS)
                    .addComponent(btnActualizarAS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Asiento Sala:"));

        TablaAsiento_Sala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdAsientoSala", "IdSala", "IdAsiento", "Disponibilidad"
            }
        ));
        TablaAsiento_Sala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAsiento_SalaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaAsiento_Sala);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignacion de salas - asientos"));

        jLabel14.setText("Sala escogida");

        jLabel16.setText("Formato");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignacion autmatica", jPanel11);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la sala"));

        jLabel1.setText("IdAsientoSala");

        jTFIdAsientoSala.setEditable(false);
        jTFIdAsientoSala.setEnabled(false);

        jLabel4.setText("Id del Asiento");

        btnLimpiar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTFIdAsiento.setEditable(false);
        jTFIdAsiento.setEnabled(false);
        jTFIdAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIdAsientoActionPerformed(evt);
            }
        });

        jLabel5.setText("Id de la Sala");

        jTFIdSala.setEditable(false);
        jTFIdSala.setEnabled(false);

        cbmDisponibilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Ocupado" }));
        cbmDisponibilidad.setSelectedIndex(-1);
        cbmDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmDisponibilidadActionPerformed(evt);
            }
        });

        jLabel2.setText("Disponibilidad");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("(Seleccione la fila en la Tabla Sala)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("(Seleccione la fila en la Tabla Asiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbmDisponibilidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTFIdAsientoSala)
                                            .addComponent(jTFIdSala, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFIdAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFIdAsientoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTFIdSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFIdAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbmDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignacion manual", jPanel12);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Archivos");

        Pelicula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Pelicula.setText("Pelicula ");
        Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeliculaActionPerformed(evt);
            }
        });
        jMenu2.add(Pelicula);

        Sala.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Sala.setText("Sala/Asiento");
        Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaActionPerformed(evt);
            }
        });
        jMenu2.add(Sala);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Funcion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JBAgregarASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarASActionPerformed
        int idSala = Integer.parseInt(jTFIdSala.getText());
        int idAsiento = Integer.parseInt(jTFIdAsiento.getText());
        boolean flag = true;
        if (cbmDisponibilidad.getSelectedIndex()<0||jTFIdSala.getText().equals("")||jTFIdAsiento.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios, por favor ingrese los datos");
        }
        else
        {  
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de agregar ?", "Alerta!", JOptionPane.YES_NO_OPTION);          
            if(resp == JOptionPane.YES_OPTION)
            {
                for( int i = 0; i < TablaAsiento_Sala.getRowCount(); i++)
                {
                    int aux_idSala = (int) TablaAsiento_Sala.getValueAt(i, 1);
                    int aux_idAsiento = (int) TablaAsiento_Sala.getValueAt(i, 2);
                    if ((aux_idAsiento == idAsiento) && (aux_idSala == idSala))
                    {
                        flag = false;
                    }
                }
                if(flag)
                {
                    try 
                    {
                        String sql = "insert into asiento_sala (IdSalaA,IdAsientoS,Disponibilidad) values("+idSala+","+idAsiento+","+auxDisponibilidad+")";
                        op.opcioness(sql);
                        JOptionPane.showMessageDialog(null, "Se agrego con exitosamente");
                        jTFIdAsientoSala.setText("");
                        jTFIdSala.setText("");
                        jTFIdAsiento.setText("");
                        cbmDisponibilidad.setSelectedIndex(-1);
                        op.cargarTabla(modeloAsiento_Sala, TablaAsiento_Sala, nombreTablaAS, TitulosAS, idTablaAS);                      
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar agregar ");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"No se puede agregar nuevamente la misma silla a la sala mas de una vez, agregacion cancelada");
                }

            }
            else
            {
                JOptionPane.showMessageDialog(null, "Agregracion cancelada");
            }
        }
        TablaAsiento.clearSelection();
        TablaSala.clearSelection();  
        jTFIdAsientoSala.setText("");
        jTFIdSala.setText("");
        jTFIdAsiento.setText("");
        cbmDisponibilidad.setSelectedIndex(-1);
    }//GEN-LAST:event_JBAgregarASActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        jTFIdAsientoSala.setText("");
        jTFIdSala.setText("");
        jTFIdAsiento.setText("");
        cbmDisponibilidad.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void JBEliminarASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarASActionPerformed
        int fila = TablaAsiento_Sala.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila que desea eliminar, por favor, seleccione la fila que desea eliminar");
        }else{ 
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try { 
                String sql = "delete from asiento_sala where IdAsiento_Sala="+pktablaAsientoSala;
                op.opcioness(sql);
                JOptionPane.showMessageDialog(null, "Se elimino exitosamente el asiento");
                jTFIdAsientoSala.setText("");
                jTFIdSala.setText("");
                jTFIdAsiento.setText("");
                cbmDisponibilidad.setSelectedIndex(-1);
                op.cargarTabla(modeloAsiento_Sala, TablaAsiento_Sala, nombreTablaAS, TitulosAS, idTablaAS);
            }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al eliminar");
                } 
            }else {
                JOptionPane.showMessageDialog(null, "Eliminacion cancelada");
            }
        }
    }//GEN-LAST:event_JBEliminarASActionPerformed

    private void btnActualizarASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarASActionPerformed
        int idSala = Integer.parseInt(jTFIdSala.getText());
        int idAsiento = Integer.parseInt(jTFIdAsiento.getText());
        if (cbmDisponibilidad.getSelectedIndex()<0||jTFIdSala.getText().equals("")||jTFIdAsiento.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios, por favor ingrese los datos");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de actualizar?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try{
                    String sql = "UPDATE asiento_sala SET IdSalaA="+idSala+", IdAsientoS="+idAsiento+", Disponibilidad="+auxDisponibilidad+" WHERE IdAsiento_Sala="+pktablaAsientoSala;
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null,"Datos actualizados correctamente.");
                    jTFIdAsientoSala.setText("");
                    jTFIdSala.setText("");
                    jTFIdAsiento.setText("");
                    cbmDisponibilidad.setSelectedIndex(-1);
                    op.cargarTabla(modeloAsiento_Sala, TablaAsiento_Sala, nombreTablaAS, TitulosAS, idTablaAS);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar actualizar.");
                }
            }else {
            JOptionPane.showMessageDialog(null, "Actualización cancelada");
            }
        }
    }//GEN-LAST:event_btnActualizarASActionPerformed

    private void TablaSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSalaMouseClicked
        int fila = TablaSala.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila");
        }else{
            pktablaSala =(int) TablaSala.getValueAt(fila, 0);
            String pk = TablaSala.getValueAt(fila, 0).toString();
            jTFIdSala.setText(pk);
            
            idSala = (int) TablaSala.getValueAt(fila, 0);
            formato = (String)TablaSala.getValueAt(fila, 1);
            jTFSala.setText(TablaSala.getValueAt(fila, 0).toString());
            switch (formato) {
                case "Sala 2D":
                    cbmFormato.setSelectedIndex(0);
                    break;
                case "Sala 4D":
                    cbmFormato.setSelectedIndex(1);
                    break;
                case "Sala VIP":
                    cbmFormato.setSelectedIndex(2);
                    break;
                default:
                    break;
            }
        }
        
    }//GEN-LAST:event_TablaSalaMouseClicked

    private void TablaAsientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAsientoMouseClicked
        int fila = TablaAsiento.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila");
        }else{
            pktablaAsiento = (int) TablaAsiento.getValueAt(fila, 0);
            String pk = TablaAsiento.getValueAt(fila, 0).toString();
            jTFIdAsiento.setText(pk);
            idAsiento = (int) TablaAsiento.getValueAt(fila, 0);
            String idAssiento = TablaAsiento.getValueAt(fila, 0).toString();
            String filat = TablaAsiento.getValueAt(fila,1).toString();
            String columna = TablaAsiento.getValueAt(fila,2).toString();
            jTFIdAsiento.setText(idAssiento);
            jTFFila.setText(filat);
            jTFColumna.setText(columna);
        }
    }//GEN-LAST:event_TablaAsientoMouseClicked

    private void cbmDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmDisponibilidadActionPerformed
        switch (cbmDisponibilidad.getSelectedIndex()) {
            case 0 :
            auxDisponibilidad = 1;//verdadero
            break;
            case 1 :
            auxDisponibilidad = 0;//falso
            break;
            default:
            break;
        }
    }//GEN-LAST:event_cbmDisponibilidadActionPerformed

    private void jTFIdAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIdAsientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdAsientoActionPerformed

    private void TablaAsiento_SalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAsiento_SalaMouseClicked
        int fila = TablaAsiento_Sala.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila");
        }else{
            pktablaAsientoSala = (int) TablaAsiento_Sala.getValueAt(fila, 0);
            String pktablaAsientoSalas = TablaAsiento_Sala.getValueAt(fila, 0).toString();
            String idAsiento = TablaAsiento_Sala.getValueAt(fila, 1).toString();
            String idSala=TablaAsiento_Sala.getValueAt(fila, 2).toString();
            jTFIdAsientoSala.setText(pktablaAsientoSalas);
            jTFIdAsiento.setText(idAsiento);
            jTFIdSala.setText(idSala);
            switch (auxDisponibilidad) {
               case 1:
                cbmDisponibilidad.setSelectedIndex(0);
                break;
               case 0:
                cbmDisponibilidad.setSelectedIndex(1);
                break;
               default:
                break;
            }
        }
    }//GEN-LAST:event_TablaAsiento_SalaMouseClicked

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        jTFSala.setText("");
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnAgregrarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregrarSalaActionPerformed
        if (cbmFormato.getSelectedIndex()<0) {
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios, por favor ingrese los datos");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de agregar la siguiente sala?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try {
                    String sql = "insert into sala(Tipo)values ('"+formato+"')";
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null, "Se agrego con exito una nueva Sala");
                    jTFSala.setText("");
                    cbmFormato.setSelectedIndex(-1);
                    //op.cargarTablaSala(modelo,Tabla);
                    op.cargarTabla(modeloSala, TablaSala, nombreTablaSala, TitulosSala, idTablaSala);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar agregar una nueva Sala");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Agregracion cancelada");
                jTFSala.setText("");
            }
        }
        TablaSala.clearSelection();
    }//GEN-LAST:event_btnAgregrarSalaActionPerformed

    private void btnEliminarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSalaActionPerformed
        int fila = TablaSala.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la sala que desea eliminar, por favor, seleccione la sala que desea eliminar");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar la siguiente sala?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try {
                    String sql = "delete from sala where IdSala="+idSala;
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null, "Se ha eliminado la sala");
                    jTFSala.setText("");
                    cbmFormato.setSelectedIndex(-1);
                    op.cargarTabla(modeloSala, TablaSala, nombreTablaSala, TitulosSala, idTablaSala);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al eliminar la sala");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Eliminacion cancelada");
            }
        }
        TablaSala.clearSelection();
    }//GEN-LAST:event_btnEliminarSalaActionPerformed

    private void btnActualizarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSalaActionPerformed

        if (cbmFormato.getSelectedIndex()<0||jTFSala.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios, por favor ingrese los datos");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de actualizar la siguiente sala?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try{
                    String sql = "UPDATE sala SET Tipo='"+formato+"' WHERE IdSala="+idSala;
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null,"Datos actualizados correctamente.");
                    jTFSala.setText("");
                    cbmFormato.setSelectedIndex(-1);
                    //op.cargarTablaSala(modelo,Tabla);
                    op.cargarTabla(modeloSala, TablaSala, nombreTablaSala, TitulosSala, idTablaSala);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar actualizar.");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Actualización cancelada");
            }
        }
        TablaSala.clearSelection();
    }//GEN-LAST:event_btnActualizarSalaActionPerformed

    private void cbmFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmFormatoActionPerformed
        switch (cbmFormato.getSelectedIndex()) {
            case 0 :
            formato = "Sala 2D";
            break;
            case 1 :
            formato = "Sala 4D";
            break;
            case 2:
            formato = "Sala VIP";
            break;
        }
    }//GEN-LAST:event_cbmFormatoActionPerformed

    private void JBAgregarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarAsientoActionPerformed
        String fila = jTFFila.getText();
        int columna = Integer.parseInt(jTFColumna.getText());
        if (fila.equals("") || jTFColumna.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios, por favor ingrese los datos");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de agregar el siguiente asiento?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try{
                    String sql = "insert into asiento (Fila,Columna) values ('"+fila+"',"+columna+")";
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null, "Se agrego con exito un nuevo asiento");
                    jTFFila.setText("");
                    jTFColumna.setText("");
                    jTFIdAsiento.setText("");
                    op.cargarTabla(modeloAsiento, TablaAsiento, nombreTablaAsiento, TitulosAsiento, idTablaAsiento);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar agregar una nueva Pelicula");
                }
                op.cargarTabla(modeloAsiento, TablaAsiento, nombreTablaAsiento, TitulosAsiento, idTablaAsiento);
            }else{
                JOptionPane.showMessageDialog(null, "Agregracion cancelada");
                jTFFila.setText("");
                jTFColumna.setText("");
                jTFIdAsiento.setText("");
            }
        }
        TablaAsiento.clearSelection();
    }//GEN-LAST:event_JBAgregarAsientoActionPerformed

    private void JBEliminarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarAsientoActionPerformed
        int fila = TablaAsiento.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado el asiento que desea eliminar, por favor, seleccione el asiento que desea eliminar");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar el siguiente asiento?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try {
                    String sql = "delete from asiento where IdAsiento="+idAsiento;
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null, "Se elimino exitosamente el asiento");
                    jTFFila.setText("");
                    jTFColumna.setText("");
                    jTFIdAsiento.setText("");
                    op.cargarTabla(modeloAsiento, TablaAsiento, nombreTablaAsiento, TitulosAsiento, idTablaAsiento);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al eliminar el asiento");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Eliminacion cancelada");
            }
        }
        TablaAsiento.clearSelection();
    }//GEN-LAST:event_JBEliminarAsientoActionPerformed

    private void btnActualizarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAsientoActionPerformed
        String fila = jTFFila.getText();
        int columna = Integer.parseInt(jTFColumna.getText());
        int filaTabla = TablaAsiento.getSelectedRow();
        if (filaTabla < 0) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado el asiento que desea eliminar, por favor, seleccione el asiento que desea eliminar");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de actualizar los siguientes datos", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try{
                    String sql = "UPDATE asiento SET Fila='"+fila+"',Columna="+columna+" WHERE IdAsiento="+idAsiento;
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null,"Datos actualizados correctamente.");
                    jTFFila.setText("");
                    jTFColumna.setText("");
                    jTFIdAsiento.setText("");
                    op.cargarTabla(modeloAsiento, TablaAsiento, nombreTablaAsiento, TitulosAsiento, idTablaAsiento);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar actualizar.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Actualización cancelada");
            }
        }
        TablaAsiento.clearSelection();
    }//GEN-LAST:event_btnActualizarAsientoActionPerformed

    private void btnLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar2ActionPerformed
        jTFIdAsiento.setText("");
        jTFColumna.setText("");
        jTFFila.setText("");
    }//GEN-LAST:event_btnLimpiar2ActionPerformed

    private void jTFColumnaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFColumnaKeyTyped
        this.validadorNumero(evt);
    }//GEN-LAST:event_jTFColumnaKeyTyped

    private void jTFFilaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFilaKeyTyped
        char variable = evt.getKeyChar();
        if (Character.isDigit(variable)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTFFilaKeyTyped

    private void PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeliculaActionPerformed
        JFPelicula jfpelicula = new JFPelicula ();
        jfpelicula.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PeliculaActionPerformed

    private void SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaActionPerformed
        JFAsiento_SalaUnido jfsala = new  JFAsiento_SalaUnido();
        jfsala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFFuncion jfuncion = new  JFFuncion();
        jfuncion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFCliente jcliente = new  JFCliente();
        jcliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    public void validadorNumero (java.awt.event.KeyEvent evt){
         char variable = evt.getKeyChar();
        if (Character.isLetter(variable)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros ","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAsiento_SalaUnido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAsiento_SalaUnido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAsiento_SalaUnido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAsiento_SalaUnido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAsiento_SalaUnido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAgregarAS;
    private javax.swing.JButton JBAgregarAsiento;
    private javax.swing.JButton JBEliminarAS;
    private javax.swing.JButton JBEliminarAsiento;
    private javax.swing.JMenuItem Pelicula;
    private javax.swing.JMenuItem Sala;
    private javax.swing.JTable TablaAsiento;
    private javax.swing.JTable TablaAsiento_Sala;
    private javax.swing.JTable TablaSala;
    private javax.swing.JButton btnActualizarAS;
    private javax.swing.JButton btnActualizarAsiento;
    private javax.swing.JButton btnActualizarSala;
    private javax.swing.JButton btnAgregrarSala;
    private javax.swing.JButton btnEliminarSala;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnLimpiar2;
    private javax.swing.JComboBox<String> cbmDisponibilidad;
    private javax.swing.JComboBox<String> cbmFormato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTFColumna;
    private javax.swing.JTextField jTFFila;
    private javax.swing.JTextField jTFIdAsiento;
    private javax.swing.JTextField jTFIdAsiento1;
    private javax.swing.JTextField jTFIdAsientoSala;
    private javax.swing.JTextField jTFIdSala;
    private javax.swing.JTextField jTFSala;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
