/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaAdministracion;

import Negocio.Opciones;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JFFuncion extends javax.swing.JFrame {

     DefaultTableModel modeloPelicula,modeloSala,modeloFuncion;
    Opciones op;
    String auxHorario;
    String formato;
    int pktablaPelicula,pktablaSala,pktablaFuncion, idSala;
    boolean flag = false;
    
    
    //tabla pelicula
    int idTablaPelicula=3;
       String[] TitulosPelicula={"IdPelicula","Titulo","Idioma"};
       String nombreTablaPelicula = "SELECT * FROM pelicula";
    //tabla sala
     int idTablaSala=2;
       String[] TitulosSala={"IdSala","Tipo"};
       String nombreTablaSala = "SELECT * FROM sala";
    //tabla asientosala
     int idTablaFuncion=6;
       String[] TitulosFuncion={"IdFuncion","Duracion","IdSala","Formato","IdPelicula","cargSala"};
       String nombreTablaFuncion = "SELECT * FROM funcion";
    public JFFuncion() {
        initComponents();
        setLocationRelativeTo(null);
        //tabla sala 
        modeloPelicula = new DefaultTableModel();
        modeloPelicula.addColumn("IdPelicula");
        modeloPelicula.addColumn("Titulo");
        modeloPelicula.addColumn("Idioma");
        TablaPelicula.setModel(modeloPelicula);
        //tabla asiento
        modeloSala = new DefaultTableModel();
        modeloSala.addColumn("IdSala");
        modeloSala.addColumn("Tipo");
        TablaSala.setModel(modeloSala);
        //tabla asiento sala
        modeloFuncion = new DefaultTableModel();
        modeloFuncion.addColumn("IdFuncion");
        modeloFuncion.addColumn("Duracion");
        modeloFuncion.addColumn("IdSala");
        modeloFuncion.addColumn("Formato");
        modeloFuncion.addColumn("IdPelicula");
        modeloFuncion.addColumn("cargSala");  
        Tablafuncion.setModel(modeloFuncion);
        //
        op = new Opciones();
        op.cargarTabla(modeloPelicula, TablaPelicula, nombreTablaPelicula, TitulosPelicula, idTablaPelicula);
        op.cargarTabla(modeloSala, TablaSala, nombreTablaSala, TitulosSala, idTablaSala);
        op.cargarTabla(modeloFuncion, Tablafuncion, nombreTablaFuncion, TitulosFuncion, idTablaFuncion);
        ImageIcon limpiar= new ImageIcon(getClass().getResource("/Imagenes/borrar.png"));
        ImageIcon icono = new ImageIcon (limpiar.getImage(
        ).getScaledInstance(btnLimpiar.getWidth(),btnLimpiar.getHeight(),Image.SCALE_DEFAULT));
        btnLimpiar.setIcon(icono);
        btnLimpiar.setContentAreaFilled(false);
        this.cbmFormato.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaPelicula = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFFuncion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jTFIdSala = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFIdPelicula = new javax.swing.JTextField();
        cbmHorario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbmFormato = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        JBAgregar = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablafuncion = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaSala = new javax.swing.JTable();
        AgregarASFunciones = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Pelicula = new javax.swing.JMenuItem();
        Sala = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pelicula"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("(Seleccione la fila deseada)");

        TablaPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPelicula", "Titulo", "Idioma"
            }
        ));
        TablaPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPeliculaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaPelicula);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la funcion"));

        jLabel1.setText("IdFuncion");

        jTFFuncion.setEditable(false);
        jTFFuncion.setEnabled(false);
        jTFFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFuncionActionPerformed(evt);
            }
        });

        jLabel4.setText("Id Sala");

        btnLimpiar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTFIdSala.setEditable(false);
        jTFIdSala.setEnabled(false);

        jLabel5.setText("Id Pelicula");

        jTFIdPelicula.setEditable(false);
        jTFIdPelicula.setEnabled(false);

        cbmHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00 - 10:00", "10:15 - 12:15", "12:30 - 14:30", "14:45 - 16:45", "17:00 - 19:00", "19:15 - 21:15", "21:30 - 23:30", "23:30 - 01:00" }));
        cbmHorario.setSelectedIndex(-1);
        cbmHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmHorarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Horario");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("(Seleccione la fila en la Tabla Sala)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("(Seleccione la fila en la Tabla Asiento");

        jLabel10.setText("Formato");

        cbmFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 2D", "Sala 3D", "Sala VIP" }));
        cbmFormato.setSelectedIndex(-1);
        cbmFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmFormatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbmHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTFFuncion)
                                        .addComponent(jTFIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTFIdSala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbmFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))))
                .addGap(32, 32, 32)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFIdSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbmHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbmFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        JBAgregar.setText("Agregar");
        JBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarActionPerformed(evt);
            }
        });

        JBEliminar.setText("Eliminar");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(JBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBEliminar)
                    .addComponent(JBAgregar)
                    .addComponent(btnActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Asiento Sala:"));

        Tablafuncion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdFuncion", "Horario", "IdSala", "Formato", "IdPelicula"
            }
        ));
        Tablafuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablafuncionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tablafuncion);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sala:"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("(Seleccione la fila deseada)");

        TablaSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdSala", "Formato"
            }
        ));
        TablaSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSalaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaSala);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        AgregarASFunciones.setText("Agregar asiento-sala_Funciones");
        AgregarASFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarASFuncionesActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Salir.setText("salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Archivos");

        Pelicula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Pelicula.setText("Pelicula ");
        Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeliculaActionPerformed(evt);
            }
        });
        jMenu2.add(Pelicula);

        Sala.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Sala.setText("Sala/Asiento");
        Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaActionPerformed(evt);
            }
        });
        jMenu2.add(Sala);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Funcion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(AgregarASFunciones)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgregarASFunciones)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFuncionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        jTFFuncion.setText("");
        jTFIdPelicula.setText("");
        jTFIdSala.setText("");
        cbmHorario.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbmHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmHorarioActionPerformed
       switch (cbmHorario.getSelectedIndex()) {
            case 0 :
            auxHorario = "08:00 - 10:00";
            break;
            case 1 :
            auxHorario = "10:15 - 12:15";
            break;    
            case 2:
            auxHorario = "12:30 - 14:30";
            break;
            case 3:
            auxHorario = "14:45 - 16:45";
            break;
            case 4:
            auxHorario = "17:00 - 19:00";
            break;
            case 5:
            auxHorario = "19:15 - 21:15";
            break;
            case 6:
            auxHorario = "21:30 - 23:30";
            break;
            case 7:
            auxHorario = "23:30 - 01:30";
            break;
            default:
            break;
        }
    }//GEN-LAST:event_cbmHorarioActionPerformed

    private void JBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarActionPerformed
      int idSala = Integer.parseInt(jTFIdSala.getText());
        int idPelicula = Integer.parseInt(jTFIdPelicula.getText());
        boolean flag = true;       
        if (cbmHorario.getSelectedIndex()<0||jTFIdPelicula.getText().equals("")||jTFIdSala.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios, por favor ingrese los datos");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de agregar?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                
                for( int i = 0; i < Tablafuncion.getRowCount(); i++){
                    String aux_Horario = (String) Tablafuncion.getValueAt(i, 1);
                    int aux_idSala = (int) Tablafuncion.getValueAt(i, 2);
                    if ((aux_Horario.equals(auxHorario)) && (aux_idSala  == idSala)){
                        flag = false;
                        System.out.println("ya existo");
                        System.out.println(auxHorario);
                    }
                }
                if(flag){
                    try {
                        String sql = "insert into funcion (Duracion,IdSala,Formato,IdPelicula,cargSala) values ('"+auxHorario+"',"+idSala+",'"+formato+"',"+idPelicula+","+0+")";
                        System.out.println(sql);
                        op.opcioness(sql);
                        JOptionPane.showMessageDialog(null, "Se agrego con exitosamente");
                        jTFFuncion.setText("");
                        jTFIdPelicula.setText("");
                        jTFIdSala.setText("");
                        cbmHorario.setSelectedIndex(-1);
                        op.cargarTabla(modeloFuncion, Tablafuncion, nombreTablaFuncion, TitulosFuncion, idTablaFuncion);
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar agregar ");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"No se puede agregar nuevamente generar la misma funcion, agregacion cancelada");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Agregracion cancelada");
            }
        }
        TablaSala.clearSelection();
        TablaPelicula.clearSelection();
        jTFFuncion.setText("");
        jTFIdPelicula.setText("");
        jTFIdSala.setText("");
        cbmHorario.setSelectedIndex(-1);
    }//GEN-LAST:event_JBAgregarActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        int fila = Tablafuncion.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila que desea eliminar, por favor, seleccione la fila que desea eliminar");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try {
                    String sql = "delete from funcion where IdFuncion="+pktablaFuncion;
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null, "Se elimino exitosamente la funcion");
                    jTFFuncion.setText("");
                    jTFIdPelicula.setText("");
                    jTFIdSala.setText("");
                    cbmHorario.setSelectedIndex(-1);
                    op.cargarTabla(modeloFuncion, Tablafuncion, nombreTablaFuncion, TitulosFuncion, idTablaFuncion);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al eliminar");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Eliminacion cancelada");
            }
        }
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int idPelicula = Integer.parseInt(jTFIdPelicula.getText());
        int idSala = Integer.parseInt(jTFIdSala.getText());
        if (cbmHorario.getSelectedIndex()<0||jTFIdPelicula.getText().equals("")||jTFIdSala.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios, por favor ingrese los datos");
        }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de actualizar?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                try{ 
                    String sql = "UPDATE funcion SET Duracion="+auxHorario+", IdSala="+idSala+",Formato="+formato+",IdPelicula="+idPelicula+" WHERE IdFuncion="+pktablaFuncion;
                    op.opcioness(sql);
                    JOptionPane.showMessageDialog(null,"Datos actualizados correctamente.");
                    jTFFuncion.setText("");
                    jTFIdPelicula.setText("");
                    jTFIdSala.setText("");
                    cbmHorario.setSelectedIndex(-1);
                    op.cargarTabla(modeloFuncion, Tablafuncion, nombreTablaFuncion, TitulosFuncion, idTablaFuncion);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al intentar actualizar.");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Actualización cancelada");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void TablafuncionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablafuncionMouseClicked
        TablaSala.clearSelection();
        TablaPelicula.clearSelection();
        int fila = Tablafuncion.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila");
        }else{
            auxHorario = Tablafuncion.getValueAt(fila, 1).toString();
            pktablaFuncion = (int) Tablafuncion.getValueAt(fila, 0);
            String pktablaFuncion = Tablafuncion.getValueAt(fila, 0).toString();
            idSala = (int) Tablafuncion.getValueAt(fila, 2);
            String idSala = Tablafuncion.getValueAt(fila, 2).toString();
            String idPelicula=Tablafuncion.getValueAt(fila, 4).toString();
            formato = Tablafuncion.getValueAt(fila, 3).toString();
            switch (formato) {
                case "Sala 2D":
                    cbmFormato.setSelectedIndex(0);
                    break;
                case "Sala 3D":
                    cbmFormato.setSelectedIndex(1);
                    break;
                case "Sala VIP":
                    cbmFormato.setSelectedIndex(2);
                    break;
            }
            flag = (Boolean) Tablafuncion.getValueAt(fila, 5);
            jTFFuncion.setText(pktablaFuncion);
            jTFIdSala.setText(idSala);
            jTFIdPelicula.setText(idPelicula);
            switch (auxHorario) {
                case "08:00 - 10:00":
                    cbmHorario.setSelectedIndex(0);
                    break;
                case "10:15 - 12:15":
                    cbmHorario.setSelectedIndex(1);
                    break;
                case "12:30 - 14:30":
                    cbmHorario.setSelectedIndex(2);
                    break;
                case "14:45 - 16:45":
                    cbmHorario.setSelectedIndex(3);
                    break;
                case "17:00 - 19:00":
                    cbmHorario.setSelectedIndex(4);
                    break;
                case "19:15 - 21:15":
                    cbmHorario.setSelectedIndex(5);
                    break;
                case "21:30 - 23:30":
                    cbmHorario.setSelectedIndex(6);
                    break;
                case "23:30 - 01:00":
                    cbmHorario.setSelectedIndex(7);
                    break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_TablafuncionMouseClicked

    private void TablaPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPeliculaMouseClicked
        int fila = TablaPelicula.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila");
        }else{
            idTablaPelicula = (int) TablaPelicula.getValueAt(fila,0);
            String IdPelicula = TablaPelicula.getValueAt(fila,0).toString();
              jTFIdPelicula.setText(IdPelicula);
        }
    }//GEN-LAST:event_TablaPeliculaMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeliculaActionPerformed
        JFPelicula jfpelicula = new JFPelicula ();
        jfpelicula.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PeliculaActionPerformed

    private void SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaActionPerformed
        JFAsiento_SalaUnido jfsala = new  JFAsiento_SalaUnido();
        jfsala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFFuncion jfuncion = new  JFFuncion();
        jfuncion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFCliente jcliente = new  JFCliente();
        jcliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void TablaSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSalaMouseClicked
        int fila = TablaSala.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la fila");
        }else{
            pktablaSala =(int) TablaSala.getValueAt(fila, 0);
            String pk = TablaSala.getValueAt(fila, 0).toString();
            jTFIdSala.setText(pk);
            formato = (String)TablaSala.getValueAt(fila, 1);
            switch (formato) {
                case "Sala 2D":
                cbmFormato.setSelectedIndex(0);
                break;
                case "Sala 3D":
                cbmFormato.setSelectedIndex(1);
                break;
                case "Sala VIP":
                cbmFormato.setSelectedIndex(2);
                break;
                default:
                break;
            }
        }

    }//GEN-LAST:event_TablaSalaMouseClicked

    private void cbmFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmFormatoActionPerformed
        switch (cbmFormato.getSelectedIndex()) {
            case 0 :
            formato = "Sala 2D";
            break;
            case 1 :
            formato = "Sala 3D";
            break;
            case 2:
            formato = "Sala VIP";
            break;
        }
    }//GEN-LAST:event_cbmFormatoActionPerformed

    private void AgregarASFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarASFuncionesActionPerformed
        if(!flag){
            int n = op.numElemtos("SELECT * FROM asiento_sala where IdSalaA = "+idSala);
            int[] listAsientoSala = new int[n];
            listAsientoSala = op.extraerAsiento_Sala(idSala, n);            
            switch (formato) {
                case "Sala 2D":
                    for (int i = 0; i < n; i++) {
                        String sql = "insert into salafuncion_sala(IdFuncionS,IdAsiento_Sala,Disp) values ("+pktablaFuncion+","+listAsientoSala[i]+","+1+")";
                        op.opcioness(sql);
                    }
                    System.out.println("Hola soy 2d");
                    break;
                case "Sala 3D":
                    System.out.println("Hola soy 3d");
                    for (int i = 0; i < n; i++) {
                        String sql = "insert into salafuncion_sala(IdFuncionS,IdAsiento_Sala,Disp) values ("+pktablaFuncion+","+listAsientoSala[i]+","+1+")";
                        op.opcioness(sql);
                    }                    
                    break;
                case "Sala VIP":
                    for (int i = 0; i < n; i++) {
                        String sql = "insert into salafuncion_sala(IdFuncionS,IdAsiento_Sala,Disp) values ("+pktablaFuncion+","+listAsientoSala[i]+","+1+")";
                        op.opcioness(sql);
                    }                    
                    System.out.println("Hola soy VIP");
                    break;                
                default:
                     break;
            }        
        }
    }//GEN-LAST:event_AgregarASFuncionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFuncion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarASFunciones;
    private javax.swing.JButton JBAgregar;
    private javax.swing.JButton JBEliminar;
    private javax.swing.JMenuItem Pelicula;
    private javax.swing.JMenuItem Sala;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JTable TablaPelicula;
    private javax.swing.JTable TablaSala;
    private javax.swing.JTable Tablafuncion;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbmFormato;
    private javax.swing.JComboBox<String> cbmHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTFFuncion;
    private javax.swing.JTextField jTFIdPelicula;
    private javax.swing.JTextField jTFIdSala;
    // End of variables declaration//GEN-END:variables
}
