
package VistaUsuario;

import Negocio.Opciones;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public final class JFCartelera extends javax.swing.JFrame {
    
    int pk_Pelicula, pk_Asiento, pk_Funcion, pk_sala, pk_asientoSala;
    String nombre_pelicula, horario;
    DefaultTableModel TablaCineModelo, TablaFuncionModelo, modeloAsiento_Sala, modeloAsiento;
    String[] Peliculas = {
            "Thor Love and Thunder",
            "Minions the Rise of Gru",
            "LightYear",
            "Tren Bala",
            "Dragon ball Z Super Hero"
    };
    Opciones op;
    int i;
    String formato;
    
    public JFCartelera(int Usuario,String nombre){
        initComponents();
        String usuario = String.valueOf(Usuario); 
        labelID.setText(usuario);
        labelNombre.setText(nombre);
        this.setMinimumSize(new Dimension(1100, 900));
        this.setLocationRelativeTo(null);
        this.CartelPeliculaSeleccionada.setVisible(false);
        btnSiguientePeliculas.setEnabled(false);
       
        op = new Opciones();
        
        JButton[] carteles = {this.jBCartel1, this.jBCartel2, this.jBCartel3, this.jBCartel4, this.jBCartel5};
        
        int numPe = Peliculas.length;
        
        for (int i = 0; i < numPe; i++) {
            carteles[i].setIcon(setIcono("/Imagenes/"+Peliculas[i]+".jpg", carteles[i]));
            carteles[i].setPressedIcon(setIconoPresinado("/Imagenes/"+Peliculas[i]+".jpg", carteles[i], 1, 1));
        }
        //paneles
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
        
        //boleto
        ImageIcon cineloginn= new ImageIcon(getClass().getResource("/Imagenes/ticket.png"));
        ImageIcon icoono = new ImageIcon (cineloginn.getImage(
        ).getScaledInstance(jlIm.getWidth(),jlIm.getHeight(),Image.SCALE_DEFAULT));
        jlIm.setIcon(icoono);
        
        //informacion del usuario
        ImageIcon cinelogin= new ImageIcon(getClass().getResource("/Imagenes/usuario.png"));
        ImageIcon icono = new ImageIcon (cinelogin.getImage(
        ).getScaledInstance(labelusuario.getWidth(),labelusuario.getHeight(),Image.SCALE_DEFAULT));
        labelusuario.setIcon(icono);
        setIconImage(getIconImage()); 
    }
    
    public JFCartelera() {
        
        initComponents();
        this.setMinimumSize(new Dimension(1100, 700));
        this.setLocationRelativeTo(null);
        this.CartelPeliculaSeleccionada.setVisible(false);
        btnSiguientePeliculas.setEnabled(false);
        
        op = new Opciones();
        
        JButton[] carteles = {this.jBCartel1, this.jBCartel2, this.jBCartel3, this.jBCartel4, this.jBCartel5};
        
        int numPe = Peliculas.length;
        
        for (int i = 0; i < numPe; i++) {
            carteles[i].setIcon(setIcono("/Imagenes/"+Peliculas[i]+".jpg", carteles[i]));
            carteles[i].setPressedIcon(setIconoPresinado("/Imagenes/"+Peliculas[i]+".jpg", carteles[i], 1, 1));
        }
        
        //paneles 
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
        
        //boleto
        ImageIcon cineloginn= new ImageIcon(getClass().getResource("/Imagenes/ticket.png"));
        ImageIcon icoono = new ImageIcon (cineloginn.getImage(
        ).getScaledInstance(jlIm.getWidth(),jlIm.getHeight(),Image.SCALE_DEFAULT));
        jlIm.setIcon(icoono);
        
    }

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/cineicon.png"));
       return retValue;
       //setIconImage(getIconImage()); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCartelera = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnComprarBoletos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBCartel5 = new javax.swing.JButton();
        jBCartel4 = new javax.swing.JButton();
        jBCartel3 = new javax.swing.JButton();
        jBCartel2 = new javax.swing.JButton();
        jBCartel1 = new javax.swing.JButton();
        btnVerCartelera = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelPeliculas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPeliculas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTFPeliculaSelec = new javax.swing.JTextField();
        btnSiguientePeliculas = new javax.swing.JButton();
        btnRegresarPeliculas = new javax.swing.JButton();
        CartelPeliculaSeleccionada = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        PanelFunciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaFunciones2D = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaFunciones3D = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaFuncionesVIP = new javax.swing.JTable();
        btnAceptarFuncion = new javax.swing.JButton();
        Pelicula_Funcion = new javax.swing.JButton();
        btnRegresarFuncion = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PanelAsiento = new javax.swing.JPanel();
        btnSiguienteAsiento = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaAsientoSala = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        TabAuxAsiento = new javax.swing.JTable();
        btnRegresarAsiento = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PanelFactura = new javax.swing.JPanel();
        PanelBoleto = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jlIm = new javax.swing.JLabel();
        btnOtroAsiento = new javax.swing.JButton();
        btnTerminarCompra = new javax.swing.JButton();
        btnRegresarCartelera = new javax.swing.JButton();
        labelusuario = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POLICINE");
        getContentPane().setLayout(null);

        PanelCartelera.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Love and Thuder");
        PanelCartelera.add(jLabel5);
        jLabel5.setBounds(40, 540, 180, 30);

        btnComprarBoletos.setBackground(new java.awt.Color(255, 255, 153));
        btnComprarBoletos.setText("Comprar boletos");
        btnComprarBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarBoletosActionPerformed(evt);
            }
        });
        PanelCartelera.add(btnComprarBoletos);
        btnComprarBoletos.setBounds(30, 70, 130, 30);

        jLabel11.setFont(new java.awt.Font("Yu Gothic Light", 2, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ESTRENO : TREN BALA");
        PanelCartelera.add(jLabel11);
        jLabel11.setBounds(30, 20, 270, 50);

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dragon Ball");
        PanelCartelera.add(jLabel10);
        jLabel10.setBounds(900, 510, 150, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tren Bala");
        PanelCartelera.add(jLabel9);
        jLabel9.setBounds(710, 510, 100, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LightYear");
        PanelCartelera.add(jLabel8);
        jLabel8.setBounds(500, 510, 100, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Thor");
        PanelCartelera.add(jLabel7);
        jLabel7.setBounds(100, 510, 60, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Minions");
        PanelCartelera.add(jLabel6);
        jLabel6.setBounds(290, 510, 100, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hola, descubre lo nuevo");
        PanelCartelera.add(jLabel1);
        jLabel1.setBounds(30, 150, 270, 30);

        jBCartel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCartel5ActionPerformed(evt);
            }
        });
        PanelCartelera.add(jBCartel5);
        jBCartel5.setBounds(870, 200, 200, 300);
        jBCartel5.getAccessibleContext().setAccessibleDescription("");

        jBCartel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCartel4ActionPerformed(evt);
            }
        });
        PanelCartelera.add(jBCartel4);
        jBCartel4.setBounds(660, 200, 200, 300);

        jBCartel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCartel3ActionPerformed(evt);
            }
        });
        PanelCartelera.add(jBCartel3);
        jBCartel3.setBounds(450, 200, 200, 300);

        jBCartel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCartel2ActionPerformed(evt);
            }
        });
        PanelCartelera.add(jBCartel2);
        jBCartel2.setBounds(240, 200, 200, 300);

        jBCartel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCartel1ActionPerformed(evt);
            }
        });
        PanelCartelera.add(jBCartel1);
        jBCartel1.setBounds(30, 200, 200, 300);
        jBCartel1.getAccessibleContext().setAccessibleDescription("");

        btnVerCartelera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerCartelera.setText("Ver cartelera");
        btnVerCartelera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCarteleraActionPerformed(evt);
            }
        });
        PanelCartelera.add(btnVerCartelera);
        btnVerCartelera.setBounds(480, 570, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pelicula_Estreno.png"))); // NOI18N
        PanelCartelera.add(jLabel2);
        jLabel2.setBounds(0, 0, 1090, 670);

        jTabbedPane1.addTab("Cartelera", PanelCartelera);

        PanelPeliculas.setLayout(null);

        TablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "p_k", "Nombre", "Idioma"
            }
        ));
        TablaPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPeliculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPeliculas);

        PanelPeliculas.add(jScrollPane1);
        jScrollPane1.setBounds(90, 110, 465, 270);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Por favor, escoja la pelicula que desea visualizar");
        PanelPeliculas.add(jLabel3);
        jLabel3.setBounds(10, 10, 481, 32);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcione escogida"));

        jLabel4.setText("Pelicula seleccionada ");

        jTFPeliculaSelec.setEditable(false);

        btnSiguientePeliculas.setText("Siguiente");
        btnSiguientePeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientePeliculasActionPerformed(evt);
            }
        });

        btnRegresarPeliculas.setText("Regresar");
        btnRegresarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPeliculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jTFPeliculaSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguientePeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPeliculaSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguientePeliculas)
                    .addComponent(btnRegresarPeliculas))
                .addGap(13, 13, 13))
        );

        PanelPeliculas.add(jPanel5);
        jPanel5.setBounds(170, 450, 321, 120);

        CartelPeliculaSeleccionada.setBorder(new javax.swing.border.MatteBorder(null));
        CartelPeliculaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartelPeliculaSeleccionadaActionPerformed(evt);
            }
        });
        PanelPeliculas.add(CartelPeliculaSeleccionada);
        CartelPeliculaSeleccionada.setBounds(670, 70, 280, 400);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaneles.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        PanelPeliculas.add(jLabel12);
        jLabel12.setBounds(0, 0, 1100, 670);

        jTabbedPane1.addTab("Peliculas", PanelPeliculas);

        PanelFunciones.setLayout(null);

        TablaFunciones2D.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaFunciones2D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFunciones2DMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaFunciones2D);

        PanelFunciones.add(jScrollPane2);
        jScrollPane2.setBounds(510, 70, 452, 124);

        TablaFunciones3D.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaFunciones3D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFunciones3DMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaFunciones3D);

        PanelFunciones.add(jScrollPane3);
        jScrollPane3.setBounds(510, 240, 452, 109);

        TablaFuncionesVIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaFuncionesVIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFuncionesVIPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaFuncionesVIP);

        PanelFunciones.add(jScrollPane4);
        jScrollPane4.setBounds(510, 400, 452, 130);

        btnAceptarFuncion.setText("Confirmar sala");
        btnAceptarFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarFuncionActionPerformed(evt);
            }
        });
        PanelFunciones.add(btnAceptarFuncion);
        btnAceptarFuncion.setBounds(660, 550, 154, 23);

        Pelicula_Funcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelicula_FuncionActionPerformed(evt);
            }
        });
        PanelFunciones.add(Pelicula_Funcion);
        Pelicula_Funcion.setBounds(80, 90, 299, 416);

        btnRegresarFuncion.setText("Regresar");
        btnRegresarFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarFuncionActionPerformed(evt);
            }
        });
        PanelFunciones.add(btnRegresarFuncion);
        btnRegresarFuncion.setBounds(170, 550, 108, 23);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Formato VIP");
        PanelFunciones.add(jLabel20);
        jLabel20.setBounds(510, 360, 160, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel18.setText("Formato 3D");
        PanelFunciones.add(jLabel18);
        jLabel18.setBounds(510, 200, 160, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel19.setText("Formato 2D");
        PanelFunciones.add(jLabel19);
        jLabel19.setBounds(510, 40, 160, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaneles.jpg"))); // NOI18N
        PanelFunciones.add(jLabel17);
        jLabel17.setBounds(0, 0, 1090, 620);

        jTabbedPane1.addTab("Funciones", PanelFunciones);

        PanelAsiento.setLayout(null);

        btnSiguienteAsiento.setText("Siguiente");
        btnSiguienteAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteAsientoActionPerformed(evt);
            }
        });
        PanelAsiento.add(btnSiguienteAsiento);
        btnSiguienteAsiento.setBounds(750, 560, 112, 23);

        TablaAsientoSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaAsientoSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAsientoSalaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TablaAsientoSala);

        PanelAsiento.add(jScrollPane7);
        jScrollPane7.setBounds(570, 50, 452, 490);

        TabAuxAsiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(TabAuxAsiento);

        PanelAsiento.add(jScrollPane8);
        jScrollPane8.setBounds(90, 50, 452, 57);

        btnRegresarAsiento.setText("Regresar");
        btnRegresarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAsientoActionPerformed(evt);
            }
        });
        PanelAsiento.add(btnRegresarAsiento);
        btnRegresarAsiento.setBounds(40, 550, 95, 23);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/butacas.jpg"))); // NOI18N
        PanelAsiento.add(jLabel22);
        jLabel22.setBounds(130, 120, 370, 350);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaneles.jpg"))); // NOI18N
        PanelAsiento.add(jLabel21);
        jLabel21.setBounds(0, 0, 1090, 640);

        jTabbedPane1.addTab("Escoger Asiento", PanelAsiento);

        PanelFactura.setBackground(new java.awt.Color(255, 255, 255));
        PanelFactura.setLayout(null);

        PanelBoleto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("_____________________________________________");

        jLabel14.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel14.setText("TU TICKET");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("_____________________________________________");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane9.setViewportView(jTextArea3);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("_____________________________________________");

        jlIm.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jlIm.setText(".");

        javax.swing.GroupLayout PanelBoletoLayout = new javax.swing.GroupLayout(PanelBoleto);
        PanelBoleto.setLayout(PanelBoletoLayout);
        PanelBoletoLayout.setHorizontalGroup(
            PanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBoletoLayout.createSequentialGroup()
                .addGroup(PanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelBoletoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBoletoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlIm, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addGap(194, 194, 194))
            .addGroup(PanelBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBoletoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        PanelBoletoLayout.setVerticalGroup(
            PanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBoletoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlIm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PanelFactura.add(PanelBoleto);
        PanelBoleto.setBounds(220, 30, 515, 426);

        btnOtroAsiento.setText("Regresar a comprar otro asiento ");
        btnOtroAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtroAsientoActionPerformed(evt);
            }
        });
        PanelFactura.add(btnOtroAsiento);
        btnOtroAsiento.setBounds(360, 500, 240, 23);

        btnTerminarCompra.setText("Terminar Compra");
        btnTerminarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarCompraActionPerformed(evt);
            }
        });
        PanelFactura.add(btnTerminarCompra);
        btnTerminarCompra.setBounds(360, 470, 240, 23);

        btnRegresarCartelera.setText("Regresar a cartelera");
        btnRegresarCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCarteleraActionPerformed(evt);
            }
        });
        PanelFactura.add(btnRegresarCartelera);
        btnRegresarCartelera.setBounds(360, 530, 240, 23);

        jTabbedPane1.addTab("Factura", PanelFactura);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 1090, 620);

        labelusuario.setText("jLabel5");
        getContentPane().add(labelusuario);
        labelusuario.setBounds(910, 10, 50, 50);

        labelID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        labelID.setText("IDUsuario");
        getContentPane().add(labelID);
        labelID.setBounds(970, 10, 110, 15);

        labelNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        labelNombre.setText("NombreUsuario");
        getContentPane().add(labelNombre);
        labelNombre.setBounds(970, 30, 120, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCartel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCartel1ActionPerformed
        pk_Pelicula = 1;
        cargarFormatoTablas(pk_Pelicula);
        this.jTabbedPane1.setSelectedIndex(2); 
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(0, false);
        nombre_pelicula = Peliculas[pk_Pelicula-1];
        Pelicula_Funcion.setIcon(setIcono("/Imagenes/"+nombre_pelicula+".jpg", Pelicula_Funcion));
    }//GEN-LAST:event_jBCartel1ActionPerformed

    private void btnVerCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCarteleraActionPerformed
        int numColumPelic = 3;
        String[] Titulos={"IdPelicula","Titulo","Idioma"};
        String nombreTabla = "SELECT * FROM pelicula";
        TablaCineModelo = new DefaultTableModel();
        TablaCineModelo.addColumn("IdPelicula");
        TablaCineModelo.addColumn("Titulo");
        TablaCineModelo.addColumn("Idioma");
        TablaPeliculas.setModel(TablaCineModelo);
        op.cargarTabla(TablaCineModelo, TablaPeliculas, nombreTabla, Titulos, numColumPelic);        
        this.jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(0, false);
    }//GEN-LAST:event_btnVerCarteleraActionPerformed

    private void TablaPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPeliculasMouseClicked
        int fila = TablaPeliculas.getSelectedRow();  
        pk_Pelicula = (int) TablaPeliculas.getValueAt(fila,0);
        nombre_pelicula = (String)TablaPeliculas.getValueAt(fila,1);
        this.CartelPeliculaSeleccionada.setVisible(true);
        this.jTFPeliculaSelec.setText(nombre_pelicula);
        CartelPeliculaSeleccionada.setIcon(setIcono("/Imagenes/"+nombre_pelicula+".jpg", CartelPeliculaSeleccionada));     
        this.btnSiguientePeliculas.setEnabled(true);
    }//GEN-LAST:event_TablaPeliculasMouseClicked

    private void btnSiguientePeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientePeliculasActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que la pelicula que desea ver es "+nombre_pelicula+" ?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_OPTION){
            this.jTabbedPane1.setSelectedIndex(2);
            jTabbedPane1.setEnabledAt(2, true);
            jTabbedPane1.setEnabledAt(1, false);
            cargarFormatoTablas(pk_Pelicula);
            this.jTabbedPane1.setSelectedIndex(2);
            Pelicula_Funcion.setIcon(setIcono("/Imagenes/"+nombre_pelicula+".jpg", Pelicula_Funcion));
        }else{
            JOptionPane.showMessageDialog(null, "Usuario, escoja su pelicula");
            TablaPeliculas.clearSelection();
            pk_Pelicula = 0;
            nombre_pelicula = "";
            this.CartelPeliculaSeleccionada.setVisible(false);
            jTFPeliculaSelec.setText("");            
        }
    }//GEN-LAST:event_btnSiguientePeliculasActionPerformed

    private void jBCartel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCartel2ActionPerformed
        pk_Pelicula = 2;
        cargarFormatoTablas(pk_Pelicula);
        this.jTabbedPane1.setSelectedIndex(2);  
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(0, false);
        nombre_pelicula = Peliculas[pk_Pelicula-1];
        Pelicula_Funcion.setIcon(setIcono("/Imagenes/"+nombre_pelicula+".jpg", Pelicula_Funcion));
    }//GEN-LAST:event_jBCartel2ActionPerformed

    private void jBCartel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCartel3ActionPerformed
        pk_Pelicula = 3;
        cargarFormatoTablas(pk_Pelicula);
        this.jTabbedPane1.setSelectedIndex(2);  
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(0, false);
        nombre_pelicula = Peliculas[pk_Pelicula-1];
        Pelicula_Funcion.setIcon(setIcono("/Imagenes/"+nombre_pelicula+".jpg", Pelicula_Funcion));
    }//GEN-LAST:event_jBCartel3ActionPerformed

    private void btnAceptarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarFuncionActionPerformed
        int fila2D = TablaFunciones2D.getSelectedRow();
        int fila3D = TablaFunciones3D.getSelectedRow();
        int filaVIP = TablaFuncionesVIP.getSelectedRow();
        if ((fila2D < 0 && fila3D < 0 && filaVIP >= 0) || (fila2D < 0 && fila3D >= 0 && filaVIP < 0) || (fila2D >= 0 && fila3D < 0 && filaVIP < 0)) {
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de escoger la funcion?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                this.jTabbedPane1.setSelectedIndex(3);
                jTabbedPane1.setEnabledAt(3, true);
                jTabbedPane1.setEnabledAt(2, false);
                int idTablaAS = 2;
                String[] TitulosAS = {"IdAsiento_Sala", "Disp"};
                String nombreTablaAS = "SELECT * FROM salafuncion_sala where IdFuncionS = " + pk_Funcion+" and Disp = 1";
                modeloAsiento_Sala = new DefaultTableModel();
                modeloAsiento_Sala.addColumn("ID de Asiento - sala");
                modeloAsiento_Sala.addColumn("Disponibilidad");
                TablaAsientoSala.setModel(modeloAsiento_Sala);
                op.cargarTabla(modeloAsiento_Sala, TablaAsientoSala, nombreTablaAS, TitulosAS, idTablaAS);
            } else {
                TablaFunciones2D.clearSelection();
                TablaFunciones3D.clearSelection();
                TablaFuncionesVIP.clearSelection();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Eliga una funcion para continuar");

        }
    }//GEN-LAST:event_btnAceptarFuncionActionPerformed

    private void TablaFunciones2DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFunciones2DMouseClicked
        int fila = TablaFunciones2D.getSelectedRow();
        horario = (String) TablaFunciones2D.getValueAt(fila, 1);
        pk_sala = (int) TablaFunciones2D.getValueAt(fila,2);
        pk_Funcion = (int) TablaFunciones2D.getValueAt(fila,0);
        this.TablaFunciones3D.clearSelection();
        this.TablaFuncionesVIP.clearSelection();
        formato = "Sala 2D";
        
    }//GEN-LAST:event_TablaFunciones2DMouseClicked

    private void TablaFunciones3DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFunciones3DMouseClicked
        int fila = TablaFunciones3D.getSelectedRow();
        horario = (String) TablaFunciones3D.getValueAt(fila, 1);
        pk_sala = (int) TablaFunciones3D.getValueAt(fila,2);        
        pk_Funcion = (Integer)TablaFunciones3D.getValueAt(fila, 0);
        this.TablaFunciones2D.clearSelection();
        this.TablaFuncionesVIP.clearSelection();
        formato = "Sala 3D";
    }//GEN-LAST:event_TablaFunciones3DMouseClicked

    private void TablaFuncionesVIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFuncionesVIPMouseClicked
        int fila = TablaFuncionesVIP.getSelectedRow();
        horario = (String) TablaFuncionesVIP.getValueAt(fila, 1);
        pk_sala = (int) TablaFuncionesVIP.getValueAt(fila,2);        
        pk_Funcion = (Integer)TablaFuncionesVIP.getValueAt(fila, 0);
        this.TablaFunciones2D.clearSelection();
        this.TablaFunciones3D.clearSelection(); 
        formato = "Sala VIP";
    }//GEN-LAST:event_TablaFuncionesVIPMouseClicked

    private void btnSiguienteAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteAsientoActionPerformed
      int id = Integer.parseInt(labelID.getText());
      
        int butaca = TablaAsientoSala.getSelectedRow();
        if ((butaca >= 0)) {
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de escoger la siguiente butaca?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                this.jTabbedPane1.setSelectedIndex(4);
                jTabbedPane1.setEnabledAt(4, true);
                jTabbedPane1.setEnabledAt(3, false);
                 try {
                    String mysql = "Insert into boleto (IdCliente,IdFuncion,IdAsiento) Values (" + id + "," + pk_Funcion + "," + pk_Asiento + ")";//
                    op.opcioness(mysql);
                    String mysql2 = "update salafuncion_sala set disp = 0 where IdFuncionS = " + pk_Funcion + " and IdAsiento_Sala =" + pk_asientoSala;
                    op.opcioness(mysql2);
                } catch (Exception e) {
                }
                
                int idAux = Integer.parseInt(labelID.getText());
                String salida = "";
                salida += " - - - - - - - - - - Información del Boleto - - - - - - - - - - - \n\n";
                salida += "      Numero de Identificación: " + labelID.getText() + "\n";
                salida += "      Nombre del Cliente: " + labelNombre.getText() + "\n\n";
                salida += "      " + nombre_pelicula + "\n";
                salida += "      Horario: " + horario + "\n";
                String auxFila = (String) TabAuxAsiento.getValueAt(0, 1);
                int auxColumna = (Integer) TabAuxAsiento.getValueAt(0, 2);
                salida += "      Formato: " + formato + "\n";
                salida += "      Sala:    " + pk_sala + "\n";
                salida += "      Asiento: " + auxFila + auxColumna + "\n\n";
                salida += "      Precio Total: " + " USD $ 10,50" + "\n\n";
                salida += " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n";
                salida += "                  ¡Que disfrutes la película!                \n";
                salida += "                        Regresa pronto                        \n";
                jTextArea3.setText(salida);
            } else {
                TablaAsientoSala.clearSelection();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Eliga una butaca para continuar");
        }
    }//GEN-LAST:event_btnSiguienteAsientoActionPerformed

    private void TablaAsientoSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAsientoSalaMouseClicked
        int fila = TablaAsientoSala.getSelectedRow();
        pk_asientoSala  = (Integer)TablaAsientoSala.getValueAt(fila, 0);
        pk_Asiento = +op.pk(pk_asientoSala, "");
        int idTabla=3;
        String[] Titulos={"IdAsiento","Fila","Columna"};
        String nombreTabla = "SELECT * FROM asiento where IdAsiento = "+pk_Asiento;        
        modeloAsiento = new DefaultTableModel();
        modeloAsiento.addColumn("# Asiento");
        modeloAsiento.addColumn("Fila");
        modeloAsiento.addColumn("Columna");
        TabAuxAsiento.setModel(modeloAsiento);
        op.cargarTabla(modeloAsiento, TabAuxAsiento, nombreTabla, Titulos, idTabla);     
    }//GEN-LAST:event_TablaAsientoSalaMouseClicked

    private void btnComprarBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBoletosActionPerformed
        pk_Pelicula = 5;
        cargarFormatoTablas(pk_Pelicula);
        this.jTabbedPane1.setSelectedIndex(2); 
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(0, false);
        nombre_pelicula = Peliculas[pk_Pelicula-1];
    }//GEN-LAST:event_btnComprarBoletosActionPerformed

    private void Pelicula_FuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelicula_FuncionActionPerformed

    }//GEN-LAST:event_Pelicula_FuncionActionPerformed

    private void CartelPeliculaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartelPeliculaSeleccionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartelPeliculaSeleccionadaActionPerformed

    private void jBCartel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCartel4ActionPerformed
        pk_Pelicula = 5;
        cargarFormatoTablas(pk_Pelicula);
        this.jTabbedPane1.setSelectedIndex(2);
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(0, false);
        nombre_pelicula = Peliculas[pk_Pelicula-2];
        Pelicula_Funcion.setIcon(setIcono("/Imagenes/"+nombre_pelicula+".jpg", Pelicula_Funcion));
    }//GEN-LAST:event_jBCartel4ActionPerformed

    private void jBCartel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCartel5ActionPerformed
        pk_Pelicula = 4;
        cargarFormatoTablas(pk_Pelicula);
        this.jTabbedPane1.setSelectedIndex(2);  
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(0, false);
        nombre_pelicula = Peliculas[pk_Pelicula];
        Pelicula_Funcion.setIcon(setIcono("/Imagenes/"+nombre_pelicula+".jpg", Pelicula_Funcion));
    }//GEN-LAST:event_jBCartel5ActionPerformed

    private void btnRegresarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPeliculasActionPerformed
        TablaPeliculas.clearSelection();
        TablaAsientoSala.clearSelection();
        TabAuxAsiento.clearSelection();
        this.jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(2, false);
        pk_Pelicula = 0;
        nombre_pelicula = "";
        this.CartelPeliculaSeleccionada.setVisible(false);
        jTFPeliculaSelec.setText("");
        this.jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
    }//GEN-LAST:event_btnRegresarPeliculasActionPerformed

    private void btnRegresarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarFuncionActionPerformed
       TablaFunciones2D.clearSelection();
        TablaFunciones3D.clearSelection();
        TablaFuncionesVIP.clearSelection();
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(2, false);
        int numColumPelic = 3;
        String[] Titulos={"IdPelicula","Titulo","Idioma"};
        String nombreTabla = "SELECT * FROM pelicula";
        TablaCineModelo = new DefaultTableModel();
        TablaCineModelo.addColumn("IdPelicula");
        TablaCineModelo.addColumn("Titulo");
        TablaCineModelo.addColumn("Idioma");
        TablaPeliculas.setModel(TablaCineModelo);
        op.cargarTabla(TablaCineModelo, TablaPeliculas, nombreTabla, Titulos, numColumPelic);
        TablaPeliculas.clearSelection();
        pk_Pelicula = 0;
        nombre_pelicula="";
        this.CartelPeliculaSeleccionada.setVisible(false);
        jTFPeliculaSelec.setText("");
        this.jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_btnRegresarFuncionActionPerformed

    private void btnRegresarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAsientoActionPerformed
        TablaAsientoSala.clearSelection();
        TabAuxAsiento.clearSelection();
        this.jTabbedPane1.setSelectedIndex(2);
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(3, false);
        TablaFunciones2D.clearSelection();
        TablaFunciones3D.clearSelection();
        TablaFuncionesVIP.clearSelection();
    }//GEN-LAST:event_btnRegresarAsientoActionPerformed

    private void btnOtroAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtroAsientoActionPerformed
        this.jTabbedPane1.setSelectedIndex(3);
        jTabbedPane1.setEnabledAt(3, true);
        jTabbedPane1.setEnabledAt(4, false);
        TablaAsientoSala.clearSelection();
        int idTablaAS = 2;
        String[] TitulosAS = {"IdAsiento_Sala", "Disp"};
        String nombreTablaAS = "SELECT * FROM salafuncion_sala where IdFuncionS = " + pk_Funcion+" and Disp = 1";
        modeloAsiento_Sala = new DefaultTableModel();
        modeloAsiento_Sala.addColumn("ID de Asiento - sala");
        modeloAsiento_Sala.addColumn("Disponibilidad");
        TablaAsientoSala.setModel(modeloAsiento_Sala);
        op.cargarTabla(modeloAsiento_Sala, TablaAsientoSala, nombreTablaAS, TitulosAS, idTablaAS);        
    }//GEN-LAST:event_btnOtroAsientoActionPerformed

    private void btnRegresarCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCarteleraActionPerformed
         int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de regresar a cartelera?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                this.jTabbedPane1.setSelectedIndex(0);
                jTabbedPane1.setEnabledAt(0, true);
                jTabbedPane1.setEnabledAt(4, false);
            }
    }//GEN-LAST:event_btnRegresarCarteleraActionPerformed

    private void btnTerminarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarCompraActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de terminar la compra?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "Gracias por su compra vuelva pronto");
                System.exit(0);
            }
    }//GEN-LAST:event_btnTerminarCompraActionPerformed

    public Icon setIcono(String url, JButton boton)
    {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new  ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconoPresinado (String url, JButton boton, int ancho, int alto) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int weight = boton.getWidth() - ancho;
        int height = boton.getHeight() - alto;
        ImageIcon icono = new  ImageIcon(icon.getImage().getScaledInstance(weight, height, Image.SCALE_DEFAULT));
        return icono;        
    } 
    
    public void cargarFormatoTablas(int pkPelicula) //funciones
    {
        JTable[] tablasFunciones = {this.TablaFunciones2D, this.TablaFunciones3D,this.TablaFuncionesVIP};
        String[] formatos = {"'Sala 2D'","'Sala 3D'","'Sala VIP'"};
        int idTablaFuncion=5;
        String[] TitulosFuncion={"IdFuncion","Duracion","IdSala","Formato","IdPelicula"};
        
        for (int i = 0; i < 3; i++) {
            String nombreTablaFuncion = "SELECT * FROM funcion where IdPelicula = "+pkPelicula+" and Formato = "+formatos[i];
            TablaFuncionModelo = new DefaultTableModel();
            TablaFuncionModelo.addColumn("IdFuncion");
            TablaFuncionModelo.addColumn("Duracion");
            TablaFuncionModelo.addColumn("IdSala");
            TablaFuncionModelo.addColumn("Formato");
            TablaFuncionModelo.addColumn("IdPelicula");
            tablasFunciones[i].setModel(TablaFuncionModelo);
            op.cargarTabla(TablaFuncionModelo, tablasFunciones[i], nombreTablaFuncion, TitulosFuncion, idTablaFuncion);            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartelPeliculaSeleccionada;
    private javax.swing.JPanel PanelAsiento;
    private javax.swing.JPanel PanelBoleto;
    private javax.swing.JPanel PanelCartelera;
    private javax.swing.JPanel PanelFactura;
    private javax.swing.JPanel PanelFunciones;
    private javax.swing.JPanel PanelPeliculas;
    private javax.swing.JButton Pelicula_Funcion;
    private javax.swing.JTable TabAuxAsiento;
    private javax.swing.JTable TablaAsientoSala;
    private javax.swing.JTable TablaFunciones2D;
    private javax.swing.JTable TablaFunciones3D;
    private javax.swing.JTable TablaFuncionesVIP;
    private javax.swing.JTable TablaPeliculas;
    private javax.swing.JButton btnAceptarFuncion;
    private javax.swing.JButton btnComprarBoletos;
    private javax.swing.JButton btnOtroAsiento;
    private javax.swing.JButton btnRegresarAsiento;
    private javax.swing.JButton btnRegresarCartelera;
    private javax.swing.JButton btnRegresarFuncion;
    private javax.swing.JButton btnRegresarPeliculas;
    private javax.swing.JButton btnSiguienteAsiento;
    private javax.swing.JButton btnSiguientePeliculas;
    private javax.swing.JButton btnTerminarCompra;
    private javax.swing.JButton btnVerCartelera;
    private javax.swing.JButton jBCartel1;
    private javax.swing.JButton jBCartel2;
    private javax.swing.JButton jBCartel3;
    private javax.swing.JButton jBCartel4;
    private javax.swing.JButton jBCartel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTFPeliculaSelec;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel jlIm;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelusuario;
    // End of variables declaration//GEN-END:variables
}
